version: '3.3'

services:
  cafe-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cafe-backend
    volumes:
      - .:/go/src/cafe-backend
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - 3110:3000
    depends_on:
    - db
    networks:
    - cafe-backend

  db:
    image: mysql
    volumes:
      - ./db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: "Asia/Bangkok"
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 123456
    ports:
      - 3310:3306
    networks:
    - cafe-backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db 
    networks:
      - cafe-backend

networks:
  cafe-backend:
    external:
      name: cafe-backend